### ISSUE TITLE
ECONNREFUSED

### ISSUE THREAD

**Issue by donaldpipowitch** [axemclion/browser-perf#21]
Calling any URL like `$ browser-perf http://google.com` throws errors for me:

````
[ { [Error: [init({"browserName":"chrome","version":35,"chromeOptions":{"perfLoggingPrefs":{"enableTimeline":true,"traceCategories":"benchmark"},"args":["--added-by-scroll","--enable-gpu-benchmarking","--enable-thread-composting"]},"loggingPrefs":{"performance":"ALL"}})] connect ECONNREFUSED]
    code: 'ECONNREFUSED',
    errno: 'ECONNREFUSED',
    syscall: 'connect' } ]

[ { [Error: [init({"browserName":"firefox","chromeOptions":{"perfLoggingPrefs":{"enableTimeline":true,"traceCategories":"benchmark"}},"loggingPrefs":{"performance":"ALL"}})] connect ECONNREFUSED]
    code: 'ECONNREFUSED',
    errno: 'ECONNREFUSED',
    syscall: 'connect' } ]
````

I'm using `$ node -v #v0.10.35`.

**Comment by axemclion** [comment]
This tries to pick up selenium on localhost:4444. Is selenium running on that server ?

**Comment by donaldpipowitch** [comment]
No, I thought this wouldn't use selenium at all, if no `--selenium` parameter is used. Sorry, about that! That's is probably the problem.

**Comment by challapruthvi** [comment]
when I am trying to run browser-perf http://google.com . I am getting the following error
[ { [Error: [init({"browserName":"chrome","version":35,"chromeOptions":{"perfLog
gingPrefs":{"traceCategories":",blink.console,disabled-by-default-devtools.timel
ine,benchmark"},"args":["--enable-gpu-benchmarking","--enable-thread-composting"
]},"loggingPrefs":{"performance":"ALL"}})] connect ECONNREFUSED]
    code: 'ECONNREFUSED',
    errno: 'ECONNREFUSED',
    syscall: 'connect' } ]

How can I resolve this.

**Comment by axemclion** [comment]
What port is selenium running on ? It should run on 4444 if you don't specify an option.
