### ISSUE TITLE
[Question] How long will the measurements been collected after the preScript (or the action) is executed?

### ISSUE THREAD

**Issue by hy9be** [axemclion/browser-perf#24]
Just a question. Thanks!

**Comment by axemclion** [comment]
Measurements are started only after the preScript finishes, and just before action starts. It ends when the action ends. [This](https://github.com/axemclion/browser-perf/blob/master/lib/index.js#L51) should give you an idea of the order or actions. 

Note that this is NOT time based, unless your action has a timer in it, or you use the [wait action](https://github.com/axemclion/browser-perf/blob/master/lib/actions/wait.js)

**Comment by hy9be** [comment]
Got it. Thanks!
