### ISSUE TITLE
Enabling throttling of speeds when testing

### ISSUE THREAD

**Issue by inian** [axemclion/browser-perf#29]
It is very useful to test websites on multiple connection speeds such as 3G, Wi-Fi and so on and measure performance using these connections.

**Comment by axemclion** [comment]
@inian That is a good idea. I am guessing that you are looking to measure impact on rendering on slow network connections - for example, the change on frame rates when you load a CSS or a font after the page has been loaded, right ? You are not trying to measure load times of pages directly using browser-perf right ?

I think that it may not make sense to make this functionality a part of browser-perf directly. However, you should be able to set up things like [web-page-replay](https://github.com/chromium/web-page-replay) to throttle and control network speeds. I see that you already have a [bug](https://github.com/chromium/web-page-replay) opened on them. 

I personally run [Fiddler](http://www.telerik.com/fiddler) and configure it as a proxy when running tests that need network throttling. Will that work for you.

**Comment by axemclion** [comment]
Closing this bug as I believe that this should be solved outside browser-perf using other tools that can be combined with browser-perf. If you strongly feel otherwise, please re-open and we could discuss ways this can be solved inside browser-perf.
