### ISSUE TITLE
Meet an issue in testing case.

### ISSUE THREAD

**Issue by stormzh** [axemclion/browser-perf#34]
Here is the main js code I used:

```javascript
var browserPerf = require('browser-perf');
var wd = require('wd');
var options = {
    selenium: 'http://localhost:4444/wd/hub',
    browsers: ['chrome'],
    actions: 'click'
};

var browser = wd.promiseChainRemote();
browserPerf('http://www.google.com', function(err, res){/*callback*/}, options);
```

Here we define a customized action "click" in the actions which is

```javascript
require('colors');
var chai = require("chai");
var chaiAsPromised = require("chai-as-promised");
chai.use(chaiAsPromised);
chai.should();

var fs = require('fs'),
    wd = require('wd'),
    debug = require('debug');

// enables chai assertion chaining
chaiAsPromised.transferPromiseness = wd.transferPromiseness;

module.exports = function() {
    return function(browser) {
        console.log('start click');
        return browser.elementByCss('#lst-ib').click();
    };
};
```

While in the execution, the program exits with "undefined" exception. If we set a breakpoint at "console.log('start click')", we can see "browser.elementByCss" is indeed a function object. Anything goes wrong? Thanks a lot.

**Comment by axemclion** [comment]
@stormzh Were you able to get this fixed ? You basically should `require(./click.js)` instead.

**Comment by hy9be** [comment]
@axemclion I had discussion with @stormzh offline on this. It looks we have to use the ``.then()`` syntax powered by ``Q``, to avoid running into this sort of issue. Is this a known fact? If it is, we may just edit the document to mention that.

**Comment by axemclion** [comment]
Yes, the actions follow promises and you are right, we should indeed edit the documentation. Can you please change the wiki so that it benefits others too ?

**Comment by hy9be** [comment]
Just add a paragraph in the "actions" section on the page: https://github.com/axemclion/browser-perf/wiki/Node-Module---API

**Comment by axemclion** [comment]
@hy9be Awesome - thanks !!
