### ISSUE TITLE
Question: full list of traceCategories options

### ISSUE THREAD

**Issue by hy9be** [axemclion/browser-perf#36]
It looks you picked two options ``blink.console`` and ``disabled-by-default-devtools.timeline``: https://github.com/axemclion/browser-perf/blob/master/lib/metrics/TimelineMetrics.js#L22

Do you know any document that I could find the full list of the trace categories?

**Comment by axemclion** [comment]
It is basically everything you see in about:tracing "Record Dialog". 

![untitled](https://cloud.githubusercontent.com/assets/17868/8270190/2b031a22-1788-11e5-9352-9d770a830c19.png)

The "value" of each radio button can be used I guess.

**Comment by hy9be** [comment]
Got it. Thanks a lot!

**Comment by hy9be** [comment]
It seems neither ``blink.console`` nor ``disabled-by-default-devtools.timeline`` are in the list. I am on Chrome 43. Is this expected?

**Comment by axemclion** [comment]
The screen shot was also from Chrome 43 - It is called devtools.timeline. Inspecting it shows the id to be `disabled-by-default-devtools.timeline`

**Comment by hy9be** [comment]
Got it. Missed the "inspecting" part. Thanks!
