### ISSUE TITLE
Issue: The environment you requested was Unavailable

### ISSUE THREAD

**Issue by csharsha** [axemclion/browser-perf#38]
Hi,
I tried to use browser-perf, it successfully launched the hybrid app, but after some time being in idle state, it thrown the error in console as follows,

D:\SeleniumAutomation\Documents\Selenium req jar files\AppiumForWindows-1.2.0.1\Appium>browser-perf --config-file test/configfile1.json
Error: [init({"browserName":"android","chromeOptions":{"androidActivity":"com.csc.chmwardview.chndev.chmWardRound","androidPackage":"com.csc.chmwardview.chndev","perfLoggingPrefs":{"traceCategories":",blink.console,disabled-by-default-devtools.timeline"},"args":["--enable-gpu-benchmarking","--enable-thread-composting"]},"loggingPrefs":{"performance":"ALL"}})] The environment you requested was unavailable.
    at D:\SeleniumAutomation\Documents\Selenium req jar files\AppiumForWindows-1.2.0.1\Appium\node_modules\browser-perf\node_modules\wd\lib\webdriver.js:129:15
    at Request._callback (D:\SeleniumAutomation\Documents\Selenium req jar files\AppiumForWindows-1.2.0.1\Appium\node_modules\browser-perf\node_modules\wd\lib\http-utils.js:87:7)
    at Request.self.callback (D:\SeleniumAutomation\Documents\Selenium req jar files\AppiumForWindows-1.2.0.1\Appium\node_modules\browser-perf\node_modules\wd\node_modules\request\request.js:368:22)
    at Request.EventEmitter.emit (events.js:98:17)
    at Request.<anonymous> (D:\SeleniumAutomation\Documents\Selenium req jar files\AppiumForWindows-1.2.0.1\Appium\node_modules\browser-perf\node_modules\wd\node_modules\request\request.js:1219:14)
    at Request.EventEmitter.emit (events.js:117:20)
    at IncomingMessage.<anonymous> (D:\SeleniumAutomation\Documents\Selenium req jar files\AppiumForWindows-1.2.0.1\Appium\node_modules\browser-perf\node_modules\wd\node_modules\request\request.js:1167:12)
    at IncomingMessage.EventEmitter.emit (events.js:117:20)
    at _stream_readable.js:920:16
    at process._tickCallback (node.js:415:13)

Please help me resolve this and also my hybrid app has native part, how can I switch to native part 
while automating it and I also need to know where does the performance logs gets collected so that I can create custom report.

Thanks

**Comment by axemclion** [comment]
It would be hard to debug this issue without actually looking at the app. `browser-perf` simply uses appium to connect to the app. Is the `webview` in teh hybrid app destroyed after some time ?
A simple test would be to run the automation script using appium without `browser-perf` and see if you still get the same error.

**Comment by csharsha** [comment]
I have been executing the app with appium from many days and it works fine. The problem came when I used browser-perf. The AUT is an android hybrid app. Please help. And please tell the answers to my other questions above.

**Comment by csharsha** [comment]
Please help, I really need to implement this in my app. Please guide me how can I setup browser-perf to an hybrid app. I can mail you in private, I need this for performance evaluation in my app.

Thanks

**Comment by axemclion** [comment]
I do not yet understand your environment. Is there a way you can tell me what the hybrid app does ? If the app code cannot be shared, a good way to see is if you can connect to the hybrid app using selenium or appium.

**Comment by axemclion** [comment]
Closing this due to lack of response. Please re-open if needed.

**Comment by csharsha** [comment]
As mentioned above,my app is perfectly working with appium/selendroid

**Comment by axemclion** [comment]
@csharsha Sorry, I meant that I was closing since there was no action item.

**Comment by abhagupta** [comment]
I am getting the same issue. My app is just  a plain html, which opens up fine in firefox. I am running selenium server on my local machine.  The test runs fine in FF but not in Chrome . My Chrome version is latest - 48.x .  Please help.

**Comment by axemclion** [comment]
@abhagupta Are you able to simply launch the selenium scripts and get the browser working ?

**Comment by jsdevel** [comment]
I'm getting this as well.  how can I help in debugging the issue?

**Comment by axemclion** [comment]
@jsdevel Can you send in the logs ? Also, can you run any selenium tests with that config ?

**Comment by jsdevel** [comment]
Sure.  Would logcat and appium suffice?

**Comment by axemclion** [comment]
@jsdevel Yup, it would. If you are able to connect via appium using node code, and if browser-perf seems to have a problem - that would indicate that we need to fix browser-perf.
Else, there could be something about the configuration that is the issue.
