### ISSUE TITLE
CEF returns on command "GetLog"

### ISSUE THREAD

**Issue by hy9be** [axemclion/browser-perf#39]
I know this may not be the problem of browser-perf. But just want to confirm that whether we are suppose to use the tool against CEF.

The full error msg is: ``unknown error: session deleted because error encountered when notifying listeners of 'GetLog' command from unknown error: unexpected command response``

**Comment by axemclion** [comment]
Could you check if CEF responds to logTypes command ? The best way is to start up selenium and run the logType command - https://seleniumhq.github.io/selenium/docs/api/java/org/openqa/selenium/logging/LogType.html

You should see a `performance` log

**Comment by hy9be** [comment]
performance, browser, driver, client are there, when I call ```java driver.manage().logs().getAvailableLogTypes```

**Comment by hy9be** [comment]
But it looks even LogType.BROWSER also returns some error.

**Comment by axemclion** [comment]
This could be a problem with CEF, not sure what the issue is.

**Comment by hy9be** [comment]
Thanks!
