### ISSUE TITLE
Multiple Selenium addresses?

### ISSUE THREAD

**Issue by chocochik92** [axemclion/browser-perf#41]
Is there support for multiple selenium addresses? I run my tests on virtual machines and i would like to have the selenium driver running on those machines. So I tried `['http://192.168.1.126:4444/wd/hub','http://192.168.1.134:4444/wd/hub']` and it gave me this error: `TypeError: Cannot read property 'match' of undefined`

**Comment by axemclion** [comment]
At the moment, browser-perf just starts the test on one instance of selenium Are you looking to cycle through multiple instances ? You may need to write a tiny wrapper that does it.

**Comment by chocochik92** [comment]
I ended up just having different config files

**Comment by axemclion** [comment]
@chocochik92 That seems to be the right way to go. Do let me know how it goes, and I would be glad to help if other problems come up.
