### ISSUE TITLE
Unable to set proxy

### ISSUE THREAD

**Issue by ramanathanMuthuraman** [axemclion/browser-perf#42]
As I am unable to set the proxy, the requested page is not available. I tried to pass proxy config but it still didn't work. Let me know how it can be resolved. Please find the  screenshot below

![browser-perf](https://cloud.githubusercontent.com/assets/5201881/9729341/6438304c-562c-11e5-95bb-509776c75390.png)

**Comment by axemclion** [comment]
@ramanathanMuthuraman What params did you pass to set a proxy ? can you help describe the use case better pleasE?

**Comment by ramanathanMuthuraman** [comment]
Used the proxy key and passed it in options object.Please find the code in the below snapshot.

![browser-perf-code](https://cloud.githubusercontent.com/assets/5201881/9753732/86b85fc2-56de-11e5-82b9-881393fbffa5.png)

**Comment by axemclion** [comment]
browser-perf does not support proxies. Is this like a HTTP proxy ? Can you help me understand what the goal here is.

**Comment by ramanathanMuthuraman** [comment]
Yeah HTTP proxy. There is a firewall present and henceforth the error.

**Comment by axemclion** [comment]
If the proxy serves the webpage, you can simply point to the proxy in the `url` key.

**Comment by ramanathanMuthuraman** [comment]
No luck :( 
But using "ondemand.saucelabs.com" instead of localhost works.
