### ISSUE TITLE
No stats when running from Android Chrome using Selenium/Appium/Protractor

### ISSUE THREAD

**Issue by dvotion** [axemclion/browser-perf#47]
When running Browser-Perf on a Android phone - Chrome Browser through a Protractor test (Appium) and I select the metrics: TimelineMetrics and/or ChromeTracingMetrics there is no output. The Chrome browser makes notice of a new profile created and also saves a profile.json file to the downloads directory on the phone. But unfortunately never gives back the data and freezes.

When I use the other metrics  "RafRenderingStats","NetworkTimings","NetworkResources" everything works fine and I get the data back.

Looking forward from hearing your solution.

Btw: thank you for such a great tool!

**Comment by axemclion** [comment]
@dvotion, can you run `browser-perf` after you have turned on debugging ? You could do that by setting the environment variable `DEBUG` to *. 

Pasting the logs here would help debug the problem. Was there a specific site you were looking to run this with  ?

**Comment by dvotion** [comment]
@axemclion Not sure if this is what you want. In the attachment a part of the config with debug settings and the Appium log. The protractor test just runs a real simple test tot angularjs.org

[appium.txt](https://github.com/axemclion/browser-perf/files/45192/appium.txt)
[config.txt](https://github.com/axemclion/browser-perf/files/45193/config.txt)

**Comment by axemclion** [comment]
These are great, but I was actually looking for the logs that are generated when browserPerf is running. That has a way to warn when there are not enough frames to record the events that mark frame rates or Timeline configurations. 

Also in those logs, you should see a way browserPerf pulls a trace file using `adb pull` from the device to your machine - taking a look at that file will help.

You can get the logs by doing `export DEBUG=*` and then running browserPerf.

**Comment by dvotion** [comment]
I think a result of the error is that pulling the trace file from the mobile phone is not working. Chrome saves the profilerlog to the phone itself but Browserperf can't seem to pick it up using adb pull for these 2 metric groups. I've attached 2 profiler files which were saved to the phone instead of giving back to Browserperf.

[chrome-profile-results-2015-11-26-162915.txt](https://github.com/axemclion/browser-perf/files/45397/chrome-profile-results-2015-11-26-162915.txt)
[chrome-profile-results-2015-11-26-182657.txt](https://github.com/axemclion/browser-perf/files/45396/chrome-profile-results-2015-11-26-182657.txt)

**Comment by axemclion** [comment]
That should explain why browserPerf is not showing the timeline data. If you run browserPerf in debug mode, it will show the exact `adb pull` command that tries to copy the file. The issue could be that browserPerf is trying to copy the file from an incorrect location.

Can you look for that command in the debug log ?

**Comment by dvotion** [comment]
Do you have an example how to run browser-perf in debug mode?

**Comment by axemclion** [comment]
looks like protractor is throwing an error. Can I request you to run this test from browser-perf and paste the logs here - that way, the error will be better pronounced.

**Comment by dvotion** [comment]
The error in the end is thrown by Protractor because of a timeout which is caused because browser-perf is freezed. When I run the same test without Browser-Perf it goes okay. When I run the same test with BrowserPerf but without the "TimelineMetrics and ChromeTracingMetrics" there is also no error and everything goes fine. So the Browserperf with metrics "RafRenderingStats", "NetworkTimings", "NetworkResources" is also working great!

So something in BrowserPerf with the metrics "TimelineMetrics and ChromeTracingMetrics" is causing the error on a mobile device.

When I look at the debug info I see this warning, can this be the cause of the error?
bp:probes:AndroidTracingProbe W/chromium(30748): [WARNING:tracing_controller_android.cc(42)]

**Comment by dvotion** [comment]
@axemclion I've inserted a debug for the query and uncomment the debug row for the function AndroidTracingProbe.prototype.waitForLogCat_

Right now the debug logs shows the following: 

bp:metrics Initializing Metrics +0ms
  bp:probes Registering probe +4ms RafBenchmarkingProbe
  bp:probes Registering probe +117ms PerfLogProbe
  bp:probes:AndroidTracingProbe Initialize +2ms
  bp:probes Registering probe +0ms AndroidTracingProbe
  bp:probes Registering probe +2ms NavTimingProbe
  bp:probes Registering probe +2ms NetworkResourcesProbe
  bp:metrics TimelineMetrics +2ms setup called
  bp:metrics NetworkResources +1ms setup called
  bp:probes setup +1ms
  bp:probes PerfLogProbe +0ms setup called
  bp:probes AndroidTracingProbe +0ms setup called
  bp:probes NetworkResourcesProbe +1ms setup called
  bp:probes start +3ms
  bp:probes RafBenchmarkingProbe +0ms start called
  bp:selenium:runner CALL +4ms execute("(function(){var getTimeMs=(function(){if(window.performance)\ 
  bp:selenium:runner RESPONSE +829ms execute("(function(){var getTimeMs=(function(){if(window.performance)\ null
  bp:probes PerfLogProbe +1ms start called
  bp:selenium:runner CALL +0ms logTypes() 
  bp:selenium:runner RESPONSE +13ms logTypes() ["browser","driver"]
  bp:probes:PerfLogProbe Supported log types +0ms [ 'browser', 'driver' ]
  bp:probes AndroidTracingProbe +1ms start called
  bp:selenium:runner CALL +0ms sessionCapabilities() 
  bp:selenium:runner RESPONSE +9ms sessionCapabilities() {"acceptSslCerts":true,"applicationCacheEnabled":false,"browserConnect
  bp:probes:AndroidTracingProbe Starting android tracing +0ms
  bp:probes:AndroidTracingProbe $ adb shell am broadcast -a com.android.chrome.GPU_PROFILER_START -e continuous "" -e categories "benchmark,disabled-by-default-devtools.timeline" +1ms
  bp:probes:AndroidTracingProbe Query: Logging performance trace to file +1s
  bp:probes:AndroidTracingProbe >  +42ms --------- beginning of main
  bp:probes:AndroidTracingProbe >  +139ms E/chromium(31797): [ERROR:layer_tree_host_impl.cc(2121)] Forcing zero-copy tile initialization as worker context is missing
  bp:probes:AndroidTracingProbe >  +3ms W/chromium(31797): [WARNING:tracing_controller_android.cc(42)] Logging performance trace to file
  bp:probes:AndroidTracingProbe >  +1ms W/chromium(31797): [WARNING:trace_event_android.cc(192)] Couldn't write to /sys/kernel/debug/tracing/trace_marker: Bad file number
  bp:probes:AndroidTracingProbe W/chromium(31797): [WARNING:tracing_controller_android.cc(42)] Logging performance trace to file +0ms
  bp:probes NetworkResourcesProbe +0ms start called
  bp:selenium:runner CALL +2ms execute("(function(){window.__networkResources=(window.performance&&ty 
  bp:selenium:runner RESPONSE +156ms execute("(function(){window.__networkResources=(window.performance&&ty null
  bp:selenium:runner CALL +0ms eval("window.__networkResources") 
  bp:selenium:runner RESPONSE +757ms eval("window.__networkResources") [{"connectEnd":650.517000001855,"connectStart":650.517000001855,"domai
  bp:probes teardown +632ms
  bp:probes RafBenchmarkingProbe +1ms teardown called
  bp:probes:RafBenchmarkingProbe Clearing timer Interval +0ms
  bp:selenium:runner CALL +0ms eval("window.__RafRecorder.get()") 
  bp:selenium:runner RESPONSE +53ms eval("window.__RafRecorder.get()") [5068.4290000936,5704.62700002827,6126.08300009742,6139.93000006303,61
  bp:probes PerfLogProbe +1ms teardown called
  bp:probes AndroidTracingProbe +0ms teardown called
  bp:selenium:runner CALL +0ms sessionCapabilities() 
  bp:selenium:runner RESPONSE +10ms sessionCapabilities() {"acceptSslCerts":true,"applicationCacheEnabled":false,"browserConnect
  bp:probes:AndroidTracingProbe Tearing down android tracing +0ms
  bp:probes:AndroidTracingProbe $ adb shell am broadcast -a com.android.chrome.GPU_PROFILER_STOP +0ms
  bp:probes:AndroidTracingProbe Query: Profiler finished. Results are in  +931ms
  bp:probes:AndroidTracingProbe >  +50ms --------- beginning of main
  bp:probes:AndroidTracingProbe >  +145ms E/chromium(31797): [ERROR:layer_tree_host_impl.cc(2121)] Forcing zero-copy tile initialization as worker context is missing
  bp:probes:AndroidTracingProbe >  +3ms W/chromium(31797): [WARNING:tracing_controller_android.cc(42)] Logging performance trace to file
  bp:probes:AndroidTracingProbe >  +0ms W/chromium(31797): [WARNING:trace_event_android.cc(192)] Couldn't write to /sys/kernel/debug/tracing/trace_marker: Bad file number
  bp:probes:AndroidTracingProbe >  +1ms W/chromium(31843): [WARNING:keycode_converter.cc(91)] empty code string
  bp:probes:AndroidTracingProbe >  +0ms W/chromium(31843): [WARNING:keycode_converter.cc(91)] empty code string
  bp:probes:AndroidTracingProbe >  +0ms W/chromium(31843): [WARNING:keycode_converter.cc(91)] empty code string
  bp:probes:AndroidTracingProbe >  +0ms W/chromium(31843): [WARNING:keycode_converter.cc(91)] empty code string
  bp:probes:AndroidTracingProbe >  +0ms W/chromium(31843): [WARNING:keycode_converter.cc(91)] empty code string
  bp:probes:AndroidTracingProbe >  +0ms W/chromium(31843): [WARNING:keycode_converter.cc(91)] empty code string
  bp:probes:AndroidTracingProbe >  +0ms W/chromium(31843): [WARNING:keycode_converter.cc(91)] empty code string
  bp:probes:AndroidTracingProbe >  +1ms W/chromium(31843): [WARNING:keycode_converter.cc(91)] empty code string
  bp:probes:AndroidTracingProbe >  +0ms W/chromium(31843): [WARNING:keycode_converter.cc(91)] empty code string
  bp:probes:AndroidTracingProbe >  +0ms W/chromium(31843): [WARNING:keycode_converter.cc(91)] empty code string
  bp:probes:AndroidTracingProbe >  +0ms W/chromium(31843): [WARNING:keycode_converter.cc(91)] empty code string
  bp:probes:AndroidTracingProbe >  +0ms W/chromium(31843): [WARNING:keycode_converter.cc(91)] empty code string
  bp:probes:AndroidTracingProbe >  +0ms W/chromium(31843): [WARNING:keycode_converter.cc(91)] empty code string
  bp:probes:AndroidTracingProbe >  +0ms W/chromium(31843): [WARNING:keycode_converter.cc(91)] empty code string
  bp:probes:AndroidTracingProbe >  +0ms W/chromium(31843): [WARNING:keycode_converter.cc(91)] empty code string
  bp:probes:AndroidTracingProbe >  +0ms W/chromium(31843): [WARNING:keycode_converter.cc(91)] empty code string
  bp:probes:AndroidTracingProbe >  +0ms W/chromium(31843): [WARNING:keycode_converter.cc(91)] empty code string
  bp:probes:AndroidTracingProbe >  +0ms W/chromium(31843): [WARNING:keycode_converter.cc(91)] empty code string
  bp:probes:AndroidTracingProbe >  +0ms W/chromium(31843): [WARNING:keycode_converter.cc(91)] empty code string
  bp:probes:AndroidTracingProbe >  +0ms W/chromium(31843): [WARNING:keycode_converter.cc(91)] empty code string
  bp:probes:AndroidTracingProbe >  +0ms W/chromium(31843): [WARNING:keycode_converter.cc(91)] empty code string
  bp:probes:AndroidTracingProbe >  +1ms W/chromium(31843): [WARNING:keycode_converter.cc(91)] empty code string
  bp:probes:AndroidTracingProbe >  +0ms W/chromium(31843): [WARNING:keycode_converter.cc(91)] empty code string
  bp:probes:AndroidTracingProbe >  +1ms W/chromium(31797): [WARNING:trace_event_android.cc(192)] Couldn't write to /sys/kernel/debug/tracing/trace_marker: Bad file number
  bp:probes:AndroidTracingProbe >  +68ms E/chromium(32294): [ERROR:layer_tree_host_impl.cc(2121)] Forcing zero-copy tile initialization as worker context is missing
  bp:probes:AndroidTracingProbe >  +6ms W/chromium(32294): [WARNING:tracing_controller_android.cc(42)] Logging performance trace to file
  bp:probes:AndroidTracingProbe >  +1ms W/chromium(32294): [WARNING:trace_event_android.cc(192)] Couldn't write to /sys/kernel/debug/tracing/trace_marker: Bad file number
  bp:probes:AndroidTracingProbe >  +0ms W/chromium(32341): [WARNING:keycode_converter.cc(91)] empty code string
  bp:probes:AndroidTracingProbe >  +1ms W/chromium(32341): [WARNING:keycode_converter.cc(91)] empty code string
  bp:probes:AndroidTracingProbe >  +0ms W/chromium(32341): [WARNING:keycode_converter.cc(91)] empty code string
  bp:probes:AndroidTracingProbe >  +0ms W/chromium(32341): [WARNING:keycode_converter.cc(91)] empty code string
  bp:probes:AndroidTracingProbe >  +1ms W/chromium(32341): [WARNING:keycode_converter.cc(91)] empty code string
  bp:probes:AndroidTracingProbe >  +1ms W/chromium(32341): [WARNING:keycode_converter.cc(91)] empty code string
  bp:probes:AndroidTracingProbe >  +0ms W/chromium(32341): [WARNING:keycode_converter.cc(91)] empty code string
  bp:probes:AndroidTracingProbe >  +0ms W/chromium(32341): [WARNING:keycode_converter.cc(91)] empty code string
  bp:probes:AndroidTracingProbe >  +0ms W/chromium(32341): [WARNING:keycode_converter.cc(91)] empty code string
  bp:probes:AndroidTracingProbe >  +0ms W/chromium(32341): [WARNING:keycode_converter.cc(91)] empty code string
  bp:probes:AndroidTracingProbe >  +0ms W/chromium(32341): [WARNING:keycode_converter.cc(91)] empty code string
  bp:probes:AndroidTracingProbe >  +0ms W/chromium(32341): [WARNING:keycode_converter.cc(91)] empty code string
  bp:probes:AndroidTracingProbe >  +0ms W/chromium(32341): [WARNING:keycode_converter.cc(91)] empty code string
  bp:probes:AndroidTracingProbe >  +4ms W/chromium(32341): [WARNING:keycode_converter.cc(91)] empty code string
  bp:probes:AndroidTracingProbe >  +0ms W/chromium(32341): [WARNING:keycode_converter.cc(91)] empty code string
  bp:probes:AndroidTracingProbe >  +0ms W/chromium(32341): [WARNING:keycode_converter.cc(91)] empty code string
  bp:probes:AndroidTracingProbe >  +0ms W/chromium(32341): [WARNING:keycode_converter.cc(91)] empty code string
  bp:probes:AndroidTracingProbe >  +1ms W/chromium(32341): [WARNING:keycode_converter.cc(91)] empty code string
  bp:probes:AndroidTracingProbe >  +0ms W/chromium(32341): [WARNING:keycode_converter.cc(91)] empty code string
  bp:probes:AndroidTracingProbe >  +0ms W/chromium(32341): [WARNING:keycode_converter.cc(91)] empty code string
  bp:probes:AndroidTracingProbe >  +0ms W/chromium(32341): [WARNING:keycode_converter.cc(91)] empty code string
  bp:probes:AndroidTracingProbe >  +0ms W/chromium(32341): [WARNING:keycode_converter.cc(91)] empty code string
  bp:probes:AndroidTracingProbe >  +35ms W/chromium(32341): [WARNING:keycode_converter.cc(91)] empty code string
  bp:probes:AndroidTracingProbe >  +0ms W/chromium(32294): [WARNING:trace_event_android.cc(192)] Couldn't write to /sys/kernel/debug/tracing/trace_marker: Bad file number
  bp:probes:AndroidTracingProbe >  +1ms --------- beginning of system
  bp:probes:AndroidTracingProbe >  +201ms E/chromium(  525): [ERROR:layer_tree_host_impl.cc(2121)] Forcing zero-copy tile initialization as worker context is missing
  bp:probes:AndroidTracingProbe >  +6ms W/chromium(  525): [WARNING:tracing_controller_android.cc(42)] Logging performance trace to file
  bp:probes:AndroidTracingProbe >  +1ms W/chromium(  525): [WARNING:trace_event_android.cc(192)] Couldn't write to /sys/kernel/debug/tracing/trace_marker: Bad file number
  bp:probes:AndroidTracingProbe >  +0ms W/chromium(  577): [WARNING:keycode_converter.cc(91)] empty code string
  bp:probes:AndroidTracingProbe >  +0ms W/chromium(  577): [WARNING:keycode_converter.cc(91)] empty code string
  bp:probes:AndroidTracingProbe >  +0ms W/chromium(  577): [WARNING:keycode_converter.cc(91)] empty code string
  bp:probes:AndroidTracingProbe >  +1ms W/chromium(  577): [WARNING:keycode_converter.cc(91)] empty code string
  bp:probes:AndroidTracingProbe >  +0ms W/chromium(  577): [WARNING:keycode_converter.cc(91)] empty code string
  bp:probes:AndroidTracingProbe >  +0ms W/chromium(  577): [WARNING:keycode_converter.cc(91)] empty code string
  bp:probes:AndroidTracingProbe >  +0ms W/chromium(  577): [WARNING:keycode_converter.cc(91)] empty code string
  bp:probes:AndroidTracingProbe >  +0ms W/chromium(  577): [WARNING:keycode_converter.cc(91)] empty code string
  bp:probes:AndroidTracingProbe >  +0ms W/chromium(  577): [WARNING:keycode_converter.cc(91)] empty code string
  bp:probes:AndroidTracingProbe >  +0ms W/chromium(  577): [WARNING:keycode_converter.cc(91)] empty code string
  bp:probes:AndroidTracingProbe >  +1ms W/chromium(  577): [WARNING:keycode_converter.cc(91)] empty code string
  bp:probes:AndroidTracingProbe >  +0ms W/chromium(  577): [WARNING:keycode_converter.cc(91)] empty code string
  bp:probes:AndroidTracingProbe >  +0ms W/chromium(  577): [WARNING:keycode_converter.cc(91)] empty code string
  bp:probes:AndroidTracingProbe >  +0ms W/chromium(  577): [WARNING:keycode_converter.cc(91)] empty code string
  bp:probes:AndroidTracingProbe >  +1ms W/chromium(  577): [WARNING:keycode_converter.cc(91)] empty code string
  bp:probes:AndroidTracingProbe >  +0ms W/chromium(  577): [WARNING:keycode_converter.cc(91)] empty code string
  bp:probes:AndroidTracingProbe >  +0ms W/chromium(  577): [WARNING:keycode_converter.cc(91)] empty code string
  bp:probes:AndroidTracingProbe >  +0ms W/chromium(  577): [WARNING:keycode_converter.cc(91)] empty code string
  bp:probes:AndroidTracingProbe >  +0ms W/chromium(  577): [WARNING:keycode_converter.cc(91)] empty code string
  bp:probes:AndroidTracingProbe >  +0ms W/chromium(  577): [WARNING:keycode_converter.cc(91)] empty code string
  bp:probes:AndroidTracingProbe >  +0ms W/chromium(  577): [WARNING:keycode_converter.cc(91)] empty code string
  bp:probes:AndroidTracingProbe >  +0ms W/chromium(  577): [WARNING:keycode_converter.cc(91)] empty code string
  bp:probes:AndroidTracingProbe >  +0ms W/chromium(  577): [WARNING:keycode_converter.cc(91)] empty code string
  bp:probes:AndroidTracingProbe >  +1ms W/chromium(  525): [WARNING:trace_event_android.cc(192)] Couldn't write to /sys/kernel/debug/tracing/trace_marker: Bad file number

**Comment by dvotion** [comment]
@axemclion I think I found the reason why it's not working. When the function "stoprecordingtrace" starts, the first promise after "adb shell am broadcast -a com.android.chrome.GPU_PROFILER_STOP" waits for the logcat to return. When you comment this promise and go straight to the file parsing everything is working fine. Can you tell me a bit if this commented promise is critical for running or is it ok to leave it out. Thanks!

The function is as follows:

AndroidTracingProbe.prototype.stopRecordingTrace_ = function(browser) {
	var me = this,
		query = 'Profiler finished. Results are in ';

	debug('Tearing down android tracing');

	return this.run_('adb shell am broadcast -a com.android.chrome.GPU_PROFILER_STOP')
     //   .then(function() {
	//	return me.waitForLogCat_(query)
	//})
        .then(function(line) {

		try {
			return me.pullLogs_(line.split(query)[1].slice(0, -1));
		} catch (e) {
			debug(e);
			return Q();
		}
	}).then(function(dataStream) {
		if (dataStream) {
			// Format is {traceEvents: [{pid:...,cat:...}]}
			dataStream.forEach(function(data) {
				me.emit('data', {
					type: 'androidTracing',
					value: data
				});
			});
		}
		debug('Read all data');
	});
};

**Comment by axemclion** [comment]
Sorry for the late response, the holidays distracted me. 

@dvotion The reason to wait is that once you send the Intenet to stop GPU, you would need to wait a little before all the information is written. Logcat writes that message, indicating that the trace is written to the file, and I read it from there. 

The `waitForLogCat_` basically checks logcal for a line that says something like `Profiler finished. Results are in ` and also gives us the filename. Are you able to see that line in logcat ? 
I tried running this on my device, and it seems to work fine. This could be a phone specific issue.

Also note that in the pullLogs function, I try to change the filename [here](https://github.com/axemclion/browser-perf/blob/master/lib/probes/AndroidTracingProbe.js#L167). I had to do this since this was the location I was getting on my devices. 

Where is your file located, and what is its name ? Could that be an issue ? In your case, I see that there are a couple of issues in Logcat that say that the trace file could not be written.

**Comment by dvotion** [comment]
Hi Axemclion,

It's been a while but still experiencing the issue. When removing the mentioned promise in the start & stop action for the waitforlogcat everything goes fine.

Is it possible to build a flag in the configuration of browser-perf so we can choose if we skip this wait or not? Would be great and solve a lot.

gr. Dennis

**Comment by axemclion** [comment]
However, if we do not wait for logcat, we may run into timing issues. I think this is just a symptom and it may be worth looking deeper into the reason why it does not work. 

Could you help me locate where the tracefile is your android device ? We could have an environment variable that specifies the file location instead of a flag since I am hoping that this is not a common issue.

**Comment by dvotion** [comment]
Okay, will look into it. Very busy schedule momentarily, I'll come back to you with the new findings

**Comment by axemclion** [comment]
I dug into this a little more and found that the tags used in logcat that indicate when logging has started, or where the log file is located is now different. So, in (this commit](https://github.com/axemclion/browser-perf/commit/f982715dde7736181f15e2c7b3115eb8e7e128f3), I simply look at all of logcat to locate the info.

I have not yet pushed this to npm, but can you test this change ? YOu could simply update node_modules/browser-perf/lib/probes/AndroidTracingProbe.js in your project and see if it works ?

**Comment by axemclion** [comment]
Also note that as a result of this change, I am trying to get frames_per_sec using `DrawFrames`. This looks like a crazy high value, possibly due to an error. Looking into that now.

**Comment by axemclion** [comment]
This should be fixed with the latest release. 
Closing the issue. If not, please reopen.
