### ISSUE TITLE
Can't get it to work on Android + Cordova

### ISSUE THREAD

**Issue by rolandoldengarm** [axemclion/browser-perf#50]
First of all, great tool! However, I'm stuck.
I'm following (this guide)[https://github.com/axemclion/browser-perf/wiki/Setup-Instructions#testing-mobile-cordova-webviewhybrid-applications] and it does not work.
I've started Chromedriver 2.20 in one console, and running browser-perf in another window. The app is starting, but then stops immediately. In the chromedriver log I see this:

````
49.607][DEBUG]: Sending adb command: host:transport:emulator-5554|shell:am force-stop nzpost.provoke.mobile
[50.745][DEBUG]: Received adb response:
[50.746][SEVERE]: unknown error: session deleted because error encountered when notifying listeners of 'GetLog' command
from unknown error: unexpected command response
  (Session info: webview=39.0.0.0)
[50.750][DEBUG]: Log type 'driver' lost 1 entries on destruction
[50.752][DEBUG]: Log type 'performance' lost 240 entries on destruction
[50.754][DEBUG]: Log type 'browser' lost 1 entries on destruction
````
And, in browser-perf the following response:
````
Error: [log("performance")] Error response status: 13, , UnknownError - An unknown server-side error occurred while processing the command. Selenium error: unknown error: session deleted because error encountered when notifying listeners of 'GetLog' command
from unknown error: unexpected command response
````

I've also created tests with Protractor, and it works fine with Appium. I've also tried to run Appium (instead of Chromedriver) and change the URL to point to Appium, but that does not seem to work either; I'm not sure what to put in the configuration.

My config file is:
````
{
  "selenium": "localhost:9515",
  "browsers": [
    {
      "browserName": "android",
      "chromeOptions": {
        "androidActivity": "io.cordova.mobile.MainActivity",
        "androidPackage": "io.cordova.mobile"
      }
    }
  ]
}
````
Tested on an Android 4.4.4 device, and an Android 5.1.1 emulator.

Please help me out, thanks!

**Comment by axemclion** [comment]
@rolandoldengarm Are you still having a problem with the latest release ? If yes, I plan to look at it during this weekend.

**Comment by rolandoldengarm** [comment]
@axemclion I'll follow up next week, not working on the project right now.

**Comment by axemclion** [comment]
@rolandoldengarm Thanks - and sorry for the delay in getting back to you.

**Comment by blefebvre** [comment]
Hi @axemclion, I'm running into a similar issue with the following environment: 

- browser-perf 1.4.5
- chromedriver 2.21.371459
- adb 1.0.32
- PhoneGap CLI 6.2.1
- Nexus 5 running Android 5.0.1

To reproduce:
- clone my test repo: https://github.com/blefebvre/pg-app-perf
- build the app once, installing it on a connected Android device: `phonegap run android --device`
- start chromedriver: `./chromedriver --verbose`
- with the app running on device, kick off the Android scroll test: `node tests/android/1-slow-scroll.js`

Result:
- The app will navigate to the 'Scroll Example - slow' page; so the preScript appears to work fine
- It will then wait at this screen for a few minutes before shutting down the app with the following output in the chromedriver terminal window:
```
[146.617][INFO]: COMMAND Quit {

}
[146.617][DEBUG]: Sending adb command: host:transport:03f3cc21437ccb7d|shell:am force-stop com.brucelefebvre.PGAppPerf
[147.316][DEBUG]: Received adb response:
[147.316][INFO]: RESPONSE Quit
[147.316][DEBUG]: Log type 'driver' lost 0 entries on destruction
[147.316][DEBUG]: Log type 'performance' lost 0 entries on destruction
[147.316][DEBUG]: Log type 'browser' lost 0 entries on destruction
```
- browser-perf calls back with an array for the `err` object, but it's contents are undefined (`[ undefined ]`).

BTW: I love this tool. Thanks for all the work you've put into it!

**Comment by blefebvre** [comment]
In looking a bit closer at the logs it appears that mine is in fact a different issue. If you'd prefer that I file a separate issue for it @axemclion, just let me know.

**Comment by axemclion** [comment]
@blefebvre Sure - I was planning to investigate the entire Android issue sometime this week.

**Comment by blefebvre** [comment]
Thanks @axemclion, I've logged https://github.com/axemclion/browser-perf/issues/61.

**Comment by axemclion** [comment]
@rolandoldengarm I fixed this https://github.com/axemclion/browser-perf/commit/60477662c950913855460a6d1879920afa703d21. Closing this issue. If you still have this issue, please reopen.

**Comment by Darkoon** [comment]
I got exactly the same problem as @rolandoldengarm . Running on browser-perf 1.4.11. 

```
C:\Users\Me\Desktop>browser-perf --config-file=configfile.json
Error: [log("performance")] Error response status: 13, , UnknownError - An unkno
wn server-side error occurred while processing the command. Selenium error: unkn
own error: session deleted because error encountered when notifying listeners of
 'GetLog' command
from unknown error: unexpected command response
  (Session info: webview=39.0.0.0)
  (Driver info: chromedriver=2.22.397933 (1cab651507b88dec79b2b2a22d1943c01833cc
1b),platform=Windows NT 6.3.9600 x86_64)...
```

**Comment by axemclion** [comment]
@Darkoon Are you still getting this error ? Can you paste in the full log ? What site are you running it against ?

**Comment by Darkoon** [comment]
I'm still getting it for this config file: https://github.com/axemclion/browser-perf/blob/master/test/res/android-hybrid.config.json (with modified androidActivity and androidPackage ofc). I start my AVD and run chromedriver.exe (ver. 2.22, starts listening on port 9515). Then I go to platform-tools in android sdk and go with command: adb server-start. At last I use: browser-perf --config-file=configfile.json. After that I have errors:
 ```
Error: [log("performance")] Error response status: 13, , UnknownError - An unknown server-side error occurred while processing the command. Selenium error: unknown error: session deleted because error encountered when notifying listeners of 'GetLog' command
from unknown error: unexpected command response 
(Session info: webview=39.0.0.0)
  (Driver info: chromedriver=2.22.397933 (1cab651507b88dec79b2b2a22d1943c01833cc
1b),platform=Windows NT 6.3.9600 x86_64)
at exports.newError (C:\Users\Me\AppData\Roaming\npm\node_modules\browser-perf\node_modules\wd\lib\utils.js:139:13)
at C:\Users\Me\AppData\Roaming\npm\node_modules\browser-perf\node_modules\wd\lib\callbacks.js:75:19
at C:\Users\Me\AppData\Roaming\npm\node_modules\browser-perf\node_modules\wd\lib\webdriver.js:174:5
at Request._callback (C:\Users\Me\AppData\Roaming\npm\node_modules\browser-perf\node_modules\wd\lib\http-utils.js:87:7)
at Request.self.callback (C:\Users\Me\AppData\Roaming\npm\node_modules\browser-perf\node_modules\wd\node_modules\request\request.js:368:22)
at emitTwo (events.js:87:13)
at Request.emit (events.js:172:7)
at Request.<anonymous> (C:\Users\Me\AppData\Roaming\npm\node_modules\browser-perf\node_modules\wd\node_modules\request\request.js:1219:14)
at emitOne (events.js:82:20)
at Request.emit (events.js:169:7)
```
ChromeDriver error: 
```
[805.385][SEVERE]: unknown error: session deleted because error encountered when
 notifying listeners of 'GetLog' command
from unknown error: unexpected command response
  (Session info: webview=39.0.0.0)
```
My application in AVD is starting but crashes after a second. I tried to modify configfile.json and one configuration worked for me: 
```
{
	"selenium": "localhost:9515",
	"browsers": [{
		"browserName": "cordova",
		"chromeOptions": {
			"androidActivity": "com.myapps.Cordova2.MainActivity",
			"androidPackage": "com.myapps.Cordova2"
		}
	}]
}
```
But the log that is generated consist of few metrics (cannot find few of them in /wiki/Metrics), many of them are zeros.
