### ISSUE TITLE
What is the difference between "framesPerSec_raf" and "framesPerSec (devtools)"

### ISSUE THREAD

**Issue by dvotion** [axemclion/browser-perf#51]
How does these 2 seemingly the same metrics, "framesPerSec_raf" and "framesPerSec (devtools)", gets calculated? When running the browserperf I get different values of these 2 metrics, but they seam to be the same subject. I'm curious why they are different and which one to use as the real fps value.

Thanks :)

**Comment by axemclion** [comment]
In fact, there are 3 FPS metrics, each calculated in different ways 
- framesPerSec_raf: This is calculated using requestAnimationFrmae. This is usually the most inaccurate, but works of other browsers too. With the latest versions of Chrome, Chrome tries to call this method at regular intervals. As a result, it may not accurately correspond to when a frame is drawn. 
- framesPerSec (devtools) - this is calculated using `DrawFrame` events that Chrome generates. This is much more accurate, and usually has a 1 to 1 correspondence to when a frame is drawn. **This is the recommended method** and is also the value you see displayed in the Chrome dev tools. 
- frames_per_sec - this is how Chrome's performance testing suite called telemetry calculates frame rates. This is based on another event, that is called `BenchmarkImpl...`. This and the devtools framespersec should be very close. 

Hope that answers your question.

**Comment by dvotion** [comment]
Thank you for your answer! Very useful information
