### ISSUE TITLE
How do I include Proxy information into the usage to be able to get out of the corporate network and be able to hit Sauce Labs?

### ISSUE THREAD

**Issue by sridharangopal** [axemclion/browser-perf#52]
This looks like a great tool to add to our CI but running into one small issue using it.
How do we include Proxy information into the usage to be able to get out of the corporate network and be able to hit Sauce Labs?

**Comment by axemclion** [comment]
@sridharangopal I would suggest using [sauce connect](https://wiki.saucelabs.com/display/DOCS/Setting+Up+Sauce+Connect) for achieving this. You should be able to find more information about testing internal sites on the saucelabs website.
