### ISSUE TITLE
How to use browser-perf.Runner with Selenium running in Java program?

### ISSUE THREAD

**Issue by mwq27** [axemclion/browser-perf#55]
Is this possible at the moment?  I know it can work with Protractor, but what if our selenium tests are all written in Java and run with the ChromeDriver there?

**Comment by axemclion** [comment]
@mwq27 This is certainly possibly. All you would have to be is start the tests using selenium, get the sessionID from selenium and pass it browser-perf. 
You would then invoke browser-perf commands.

Here is an example - https://github.com/axemclion/protractor-perf/blob/master/lib/index.js

**Comment by axemclion** [comment]
Closing this with the hope that this answers your question. If not, please reopen the issue.

**Comment by mwq27** [comment]
The part I'm confused about is passing the sessionID from Java to browser-perf.  Could you explain a little more?

Thanks

**Comment by axemclion** [comment]
Basically, we need to connect browser-perf to selenium to fetch performance logs. For this, we would need the same sessionID that your java code got when it started the browser. Selenium lets any client to "attach" to an existing session and send commands - thats what browser-perf would do.

Thus, you would have to 

1. From `browser-perf`, write the [additional capabilities](https://github.com/axemclion/browser-perf/blob/master/lib/runner.js#L17) that need to be added when starting your browser
2. Use java to start a new browser session, with the required capabilities
3. Get [sessionID](http://selenium.googlecode.com/svn/trunk/docs/api/java/org/openqa/selenium/remote/RemoteWebDriver.html#getSessionId%28%29) of the session that your Java code created
3. Pause Java, run node, and start `browser-perf` to attach to that session and start perf logging
4. Once this is done, stop Node, resume your Java code 
5. After Java executes all the test instructions, run Node again with `browser-perf` to stop the tests and collect the perf numbers. 

You can find all those methods in the [runner](https://github.com/axemclion/browser-perf/blob/master/lib/runner.js#L27) object.

**Comment by mwq27** [comment]
Alright thanks for explaining.  I need this process to be more automated and was hoping to just attach to our Selenium tests in Java, but it looks like this is more of a manual process.  Looks like we'll just have to write some new scenarios specific to performance testing in Javascript instead of node.

**Comment by axemclion** [comment]
Alternatively, you could also get perf logs in Java and pare that in Java. You would have to write Java code for that though.

**Comment by mwq27** [comment]
So far, i've exported all of the perf logs from the java tests to an external file, and edited the browser-perf code to read from that file in the perfProbe.  But this doesn't seem like a long term solution, and also doesn't give me the nav timing data, since it looks like that gets calculated in the NavTimingProbe.

**Comment by axemclion** [comment]
Actually, navTiming is probably easier, if that is all you are looking for. In Java, simply executeScript to evaluate `window.performance.timing` and then pick up the results !!
