### ISSUE TITLE
QUESTION - Automated browser testing on iOS device

### ISSUE THREAD

**Issue by bigbadleroybrown** [axemclion/browser-perf#56]
Am I able to automate safari performance using 'browser-perf'?
Specifically is it possible to use 'browser-perf' to show the 'DomContentLoadedEvent' and 'CompleteLoad' events multiple times from several sites, i.e. each site would be reloaded 50 times, and each time, record the 'DomContentLoadedEvent' and 'CompleteLoad' events (both kilobytes and time to event).

**Comment by axemclion** [comment]
It is possible to do so. However, browser-perf only returns one event every run, so I suggest running browser-perf 50 times. This way, you will also not be impacted by browser optimizations like caching, etc.

**Comment by bigbadleroybrown** [comment]
Ok thanks for the quick response! 

Two more QQ's:  
1. Is browser-perf built on top of Appium, and subsequently, will be required to be installed first?
2. Will browser-perf show these metrics (DomContentLoaded and LoadEvent) out of the box for each site?

**Comment by axemclion** [comment]
@bigbadleroybrown Browser-perf is not really built on top of Appium. However, it does require Selenium or Appium to get metrics. Note that it also need a browser that is driven by selenium.

The 2 metrics are a part of networkMetrics, and are always available for each page navigation.
