### ISSUE TITLE
Action never completes with Cordova app running on Android

### ISSUE THREAD

**Issue by blefebvre** [axemclion/browser-perf#61]
When running a browser-perf test via the Node API targeting Android hardware, my test action never appears to be fired and the action eventually times out.

Environment:

browser-perf 1.4.5
chromedriver 2.21.371459
adb 1.0.32
PhoneGap CLI 6.2.1
Nexus 5 running Android 5.0.1

To reproduce:

- clone my test repo: https://github.com/blefebvre/pg-app-perf
- build the app once, installing it on a connected Android device: `phonegap run android --device`
- start chromedriver: `./chromedriver --verbose`
- with the app running on device, kick off the Android scroll test: `node tests/android/1-slow-scroll.js`

Result:

- The app will navigate to the 'Scroll Example - slow' page; so the preScript appears to work fine
- It will then wait at this screen for a few minutes before shutting down the app with the following output in the chromedriver terminal window:

```
[146.617][INFO]: COMMAND Quit {

}
[146.617][DEBUG]: Sending adb command: host:transport:03f3cc21437ccb7d|shell:am force-stop com.brucelefebvre.PGAppPerf
[147.316][DEBUG]: Received adb response:
[147.316][INFO]: RESPONSE Quit
[147.316][DEBUG]: Log type 'driver' lost 0 entries on destruction
[147.316][DEBUG]: Log type 'performance' lost 0 entries on destruction
[147.316][DEBUG]: Log type 'browser' lost 0 entries on destruction
```

- browser-perf calls back with an array for the err object, but it's contents are undefined (`[ undefined ]`).

**Comment by axemclion** [comment]
@blefebvre Looks like this is related to https://github.com/axemclion/browser-perf/issues/14. Due to a bug, looks like the code is trying to get `adb logcat` even for Android, which it should not.

**Comment by axemclion** [comment]
@blefebvre Btw, nice talk at PGDay EU.

**Comment by axemclion** [comment]
You don't even need to wait for taps and clicks, you could technically navigate to the slow page (or the fast page) and run the tests.

**Comment by axemclion** [comment]
I ran the tests now and they run. Closing the issue now.

**Comment by blefebvre** [comment]
Verified that version `1.4.7` works perfectly. Thanks @axemclion, will update my PGDay repo to reference this version and include test suites that target Android. No worries at all about the timing, I should have raised the issue sooner. Cheers!
