### ISSUE TITLE
Viewer

### ISSUE THREAD

**Issue by caffinatedmonkey** [axemclion/browser-perf#64]
Collecting this data is great, but are there ways to view it besides a table?

**Comment by blefebvre** [comment]
@caffinatedmonkey check out perfjankie for an idea of how this data can be stored and graphed over time. 

https://github.com/axemclion/perfjankie

**Comment by axemclion** [comment]
browser-perf is available as a Node module, so you could also consume it and get JSON data that can be used to graph it in a way you need.
Here are also some examples that use perjankie to view the data - http://web-perf.github.io.
