### ISSUE TITLE
browser-perf@1.4.7 VS1.4.6 has a new issue

### ISSUE THREAD

**Issue by drywind** [axemclion/browser-perf#66]
when i used browser-perf@1.4.7 version,i can't get the perfmance data,you can follow below step to confirm this issue:
win7@32 bit
android chrome apk installed in android devices

error info:[TypeError: Cannot read property 'code' of undefined]

**Comment by axemclion** [comment]
@drywind Can you set the environment variable `DEBUG=*` and run the tests ? Can you also copy the logs here ? May help with debugging. I do not have a Win7 machine, but this could be a problem on other OS also.

**Comment by drywind** [comment]
D:\node\MyNodeProject\browser-perf>mocha ./test_on_hwb_youtube.js
  mocha:suite bail undefined +0ms
  mocha:suite enableTimeouts true +16ms
  mocha:suite bail undefined +0ms
  mocha:suite timeout 2000 +421ms
  mocha:suite retries -1 +0ms
  mocha:suite enableTimeouts true +0ms
  mocha:suite slow 75 +0ms
  mocha:suite bail undefined +0ms
  mocha:suite timeout 2000 +0ms
  mocha:suite retries -1 +0ms
  mocha:suite enableTimeouts true +0ms
  mocha:suite slow 75 +0ms
  mocha:suite bail undefined +0ms
  mocha:suite timeout 600000 +0ms
  mocha:runnable timeout 600000 +0ms
  mocha:runnable enableTimeouts true +0ms
  mocha:runnable timeout 75 +0ms
  mocha:runner grep /.*/ +0ms
  mocha:runner globals ["DTRACE_NET_SERVER_CONNECTION","DTRACE_NET_STREAM_END","
DTRACE_HTTP_SERVER_REQUEST","DTRACE_HTTP_SERVER_RESPONSE","DTRACE_HTTP_CLIENT_RE
QUEST","DTRACE_HTTP_CLIENT_RESPONSE","COUNTER_NET_SERVER_CONNECTION","COUNTER_NE
T_SERVER_CONNECTION_CLOSE","COUNTER_HTTP_SERVER_REQUEST","COUNTER_HTTP_SERVER_RE
SPONSE","COUNTER_HTTP_CLIENT_REQUEST","COUNTER_HTTP_CLIENT_RESPONSE","global","p
rocess","GLOBAL","root","Buffer","clearImmediate","clearInterval","clearTimeout"
,"setImmediate","setInterval","setTimeout","console","before","after","beforeEac
h","afterEach","run","context","describe","xcontext","xdescribe","specify","it",
"xspecify","xit","XMLHttpRequest","Date","errno"] +0ms
  mocha:runner globals [] +0ms
  mocha:runner start +0ms

  mocha:runner run suite  +0ms

  mocha:runner run suite End To End Test Cases +16ms
  End To End Test Cases
  mocha:runner run suite End To End Test Cases gets enough statistics from brows
ers +0ms
    gets enough statistics from browsers
  bp:index Selenium is on localhost +0ms
  bp:metrics Initializing Metrics +0ms
  bp:probes Registering probe +249ms PerfLogProbe
  bp:probes:AndroidTracingProbe Initialize +0ms
  bp:probes Registering probe +0ms AndroidTracingProbe
  bp:probes Registering probe +16ms PerfLogProbe
  bp:probes Registering probe +0ms AndroidTracingProbe
  bp:probes Registering probe +0ms RafBenchmarkingProbe
  bp:probes Registering probe +0ms NavTimingProbe
  bp:probes Registering probe +16ms NetworkResourcesProbe
  bp:metrics TimelineMetrics +0ms setup called
  bp:metrics ChromeTracingMetrics +0ms setup called
  bp:metrics NetworkResources +0ms setup called
  bp:probes setup +0ms
  bp:probes PerfLogProbe +0ms setup called
  bp:probes AndroidTracingProbe +0ms setup called
  bp:probes:AndroidTracingProbe Setting up android tracing +0ms
  bp:probes:AndroidTracingProbe $ adb server start +0ms
  bp:probes:AndroidTracingProbe $ adb logcat -c +46ms
  bp:probes NetworkResourcesProbe +32ms setup called
  bp:index Stating browser with +0ms {"browserName":"android","chromeOptions":{"
androidPackage":"com.android.chrome","androidDeviceSerial":"192.168.206.113:5555
","perfLoggingPrefs":{}},"loggingPrefs":{"performance":"ALL"}}
  bp:selenium CALL +0ms init({"browserName":"android","chromeOptions":{"androidP
ackage":"com.a
  bp:selenium RESPONSE +4s init({"browserName":"android","chromeOptions":{"andro
idPackage":"com.a "39b9525022a19bb99439fec508642809",{"acceptSslCerts":true,"app
lication
  bp:index Session is 39b9525022a19bb99439fec508642809 +0ms
  bp:index Running Prescript +0ms
  bp:selenium CALL +0ms get("https://www.baidu.com/")
  bp:selenium RESPONSE +33s get("https://www.baidu.com/")
  bp:probes start +0ms
  bp:probes PerfLogProbe +0ms start called
  bp:selenium CALL +0ms logTypes()
  bp:selenium RESPONSE +15ms logTypes() ["performance","browser","driver"]
  bp:probes:PerfLogProbe Supported log types +0ms [ 'performance', 'browser', 'd
river' ]
  bp:selenium CALL +0ms log("performance")
  bp:selenium RESPONSE +16ms log("performance") [{"level":"INFO","message":"{\"m
essage\":{\"method\":\"Page.frameAttac
  bp:probes AndroidTracingProbe +0ms start called
  bp:probes:AndroidTracingProbe Starting android tracing +0ms
  bp:probes:AndroidTracingProbe $ adb shell pm grant com.android.chrome android.
permission.WRITE_EXTERNAL_STORAGE +0ms
  bp:probes:AndroidTracingProbe $ adb shell pm grant com.android.chrome android.
permission.READ_EXTERNAL_STORAGE +483ms
  bp:probes:AndroidTracingProbe $ adb shell 'am broadcast -a com.android.chrome.
GPU_PROFILER_START -e continuous "" -e categories "benchmark,disabled-by-default
-devtools.timeline,toplevel,disabled-by-default-devtools.timeline.frame"' +0ms
  bp:selenium CALL +2m quit()
  bp:selenium RESPONSE +655ms quit()
[TypeError: Cannot read property 'code' of undefined]
      √ Actions:do nothing (158525ms)

  mocha:runner finished running +3m

  1 passing (3m)

  mocha:runner end +0ms

**Comment by drywind** [comment]
it's very surprise,when i use chrome dev version,it(browser-perf version@1.4.7) runs well . 
D:\node\MyNodeProject\browser-perf>mocha ./test_on_hwb_youtube.js
  mocha:suite bail undefined +0ms
  mocha:suite enableTimeouts true +0ms
  mocha:suite bail undefined +15ms
  mocha:suite timeout 2000 +439ms
  mocha:suite retries -1 +0ms
  mocha:suite enableTimeouts true +0ms
  mocha:suite slow 75 +0ms
  mocha:suite bail undefined +0ms
  mocha:suite timeout 2000 +0ms
  mocha:suite retries -1 +0ms
  mocha:suite enableTimeouts true +0ms
  mocha:suite slow 75 +0ms
  mocha:suite bail undefined +0ms
  mocha:suite timeout 600000 +0ms
  mocha:runnable timeout 600000 +0ms
  mocha:runnable enableTimeouts true +0ms
  mocha:runnable timeout 75 +0ms
  mocha:runner grep /.*/ +0ms
  mocha:runner globals ["DTRACE_NET_SERVER_CONNECTION","DTRACE_NET_STREAM_END","
DTRACE_HTTP_SERVER_REQUEST","DTRACE_HTTP_SERVER_RESPONSE","DTRACE_HTTP_CLIENT_RE
QUEST","DTRACE_HTTP_CLIENT_RESPONSE","COUNTER_NET_SERVER_CONNECTION","COUNTER_NE
T_SERVER_CONNECTION_CLOSE","COUNTER_HTTP_SERVER_REQUEST","COUNTER_HTTP_SERVER_RE
SPONSE","COUNTER_HTTP_CLIENT_REQUEST","COUNTER_HTTP_CLIENT_RESPONSE","global","p
rocess","GLOBAL","root","Buffer","clearImmediate","clearInterval","clearTimeout"
,"setImmediate","setInterval","setTimeout","console","before","after","beforeEac
h","afterEach","run","context","describe","xcontext","xdescribe","specify","it",
"xspecify","xit","XMLHttpRequest","Date","errno"] +0ms
  mocha:runner globals [] +0ms
  mocha:runner start +0ms

  mocha:runner run suite  +0ms

  mocha:runner run suite End To End Test Cases +0ms
  End To End Test Cases
  mocha:runner run suite End To End Test Cases gets enough statistics from brows
ers +16ms
    gets enough statistics from browsers
  bp:index Selenium is on localhost +0ms
  bp:metrics Initializing Metrics +0ms
  bp:probes Registering probe +246ms PerfLogProbe
  bp:probes:AndroidTracingProbe Initialize +0ms
  bp:probes Registering probe +0ms AndroidTracingProbe
  bp:probes Registering probe +16ms PerfLogProbe
  bp:probes Registering probe +0ms AndroidTracingProbe
  bp:probes Registering probe +0ms RafBenchmarkingProbe
  bp:probes Registering probe +0ms NavTimingProbe
  bp:probes Registering probe +0ms NetworkResourcesProbe
  bp:metrics TimelineMetrics +0ms setup called
  bp:metrics ChromeTracingMetrics +0ms setup called
  bp:metrics NetworkResources +0ms setup called
  bp:probes setup +15ms
  bp:probes PerfLogProbe +0ms setup called
  bp:probes AndroidTracingProbe +0ms setup called
  bp:probes NetworkResourcesProbe +0ms setup called
  bp:index Stating browser with +0ms {"browserName":"android","chromeOptions":{"
androidPackage":"com.chrome.dev","androidDeviceSerial":"192.168.206.113:5555","p
erfLoggingPrefs":{"traceCategories":",blink.console,devtools.timeline,disabled-b
y-default-devtools.timeline,toplevel,disabled-by-default-devtools.timeline.frame
"}},"loggingPrefs":{"performance":"ALL"}}
  bp:selenium CALL +0ms init({"browserName":"android","chromeOptions":{"androidP
ackage":"com.c
  bp:selenium RESPONSE +4s init({"browserName":"android","chromeOptions":{"andro
idPackage":"com.c "fdca5bf3a91e41ac7128df8255006955",{"acceptSslCerts":true,"app
lication
  bp:index Session is fdca5bf3a91e41ac7128df8255006955 +0ms
  bp:index Running Prescript +0ms
  bp:selenium CALL +0ms get("https://www.baidu.com/")
  bp:selenium RESPONSE +57s get("https://www.baidu.com/")
  bp:probes start +0ms
  bp:probes PerfLogProbe +0ms start called
  bp:selenium CALL +0ms logTypes()
  bp:selenium RESPONSE +15ms logTypes() ["performance","browser","driver"]
  bp:probes:PerfLogProbe Supported log types +0ms [ 'performance', 'browser', 'd
river' ]
  bp:selenium CALL +0ms log("performance")
  bp:selenium RESPONSE +13s log("performance") [{"level":"INFO","message":"{\"me
ssage\":{\"method\":\"Tracing.dataCol
  bp:probes AndroidTracingProbe +0ms start called
  bp:probes RafBenchmarkingProbe +0ms start called
  bp:selenium CALL +15ms execute("(function(){var getTimeMs=(function(){if(windo
w.performance)\
  bp:selenium RESPONSE +47ms execute("(function(){var getTimeMs=(function(){if(w
indow.performance)\ null
  bp:probes NetworkResourcesProbe +0ms start called
  bp:selenium CALL +16ms execute("(function(){window.__networkResources=(window.
performance&&ty
  bp:probes teardown +0ms
  bp:probes PerfLogProbe +0ms teardown called
  bp:probes:PerfLogProbe Getting Performance log +0ms http://localhost:9515/sess
ion/fdca5bf3a91e41ac7128df8255006955/log
  bp:selenium RESPONSE +31ms execute("(function(){window.__networkResources=(win
dow.performance&&ty null
  bp:selenium CALL +0ms eval("window.__networkResources")
  bp:selenium RESPONSE +93ms eval("window.__networkResources") [{"connectEnd":0,
"connectStart":0,"domainLookupEnd":0,"domainLookupSta
  bp:probes AndroidTracingProbe +2s teardown called
  bp:probes RafBenchmarkingProbe +1ms teardown called
  bp:probes:RafBenchmarkingProbe Clearing timer Interval +0ms
  bp:selenium CALL +1ms eval("window.__RafRecorder.get()")
  bp:selenium RESPONSE +24ms eval("window.__RafRecorder.get()") [49802.070000001
6,49818.7370000014,49835.403000001,49852.0700000008,49
  bp:probes NavTimingProbe +0ms teardown called
  bp:selenium CALL +0ms execute("(function(){var requestAnimationFrame=(function
(){return wind
  bp:selenium RESPONSE +31ms execute("(function(){var requestAnimationFrame=(fun
ction(){return wind null
  bp:selenium CALL +0ms waitFor({"asserter":{},"timeout":600000,"pollFreq":1000}
)
  bp:selenium CALL +0ms eval("(typeof window.__navTimings !== \"undefined\")")
  bp:selenium RESPONSE +16ms eval("(typeof window.__navTimings !== \"undefined\"
)") true
  bp:selenium RESPONSE +0ms waitFor({"asserter":{},"timeout":600000,"pollFreq":1
000}) true
  bp:selenium CALL +0ms eval("window.__navTimings")
  bp:selenium RESPONSE +31ms eval("window.__navTimings") {"connectEnd":146675284
5899,"connectStart":1466752845834,"domComplete"
  bp:probes NetworkResourcesProbe +0ms teardown called
  bp:selenium CALL +0ms execute("(function(){window.__networkResources=(window.p
erformance&&ty
  bp:selenium RESPONSE +16ms execute("(function(){window.__networkResources=(win
dow.performance&&ty null
  bp:selenium CALL +0ms eval("window.__networkResources")
  bp:selenium RESPONSE +62ms eval("window.__networkResources") [{"connectEnd":0,
"connectStart":0,"domainLookupEnd":0,"domainLookupSta
  bp:metrics Getting Results +0ms
  bp:metrics Getting results from  +0ms TimelineMetrics
  bp:metrics Getting results from  +0ms ChromeTracingMetrics
  bp:metrics:RenderingStats Process ID for render process is  +0ms 29377
  bp:metrics:RenderingStats Timestamp Event name is  +0ms BenchmarkInstrumentati
on::ImplThreadRenderingStats
  bp:metrics:ChromeTracingMetrics Does not have enough frames for computing trac
ing +0ms
  bp:metrics:ChromeTracingMetrics Does not have enough frames for computing trac
ing +16ms
  bp:metrics Getting results from  +0ms RafBenchmarkingRenderingStats
  bp:metrics Getting results from  +0ms NetworkTimings
  bp:metrics Getting results from  +0ms NetworkResources
  bp:selenium CALL +0ms quit()
  bp:selenium RESPONSE +721ms quit()
[ { 'MessagePumpLibevent::OnLibeventNotification': 68.67500002682209,
    'MessagePumpLibevent::OnLibeventNotification_avg': 0.1404396728564869,
    'MessagePumpLibevent::OnLibeventNotification_max': 3.1490000002086163,
    'MessagePumpLibevent::OnLibeventNotification_count': 489,
    'ChannelReader::DispatchInputData': 0.5509999915957451,
    'ChannelReader::DispatchInputData_avg': 0.042384614738134235,
    'ChannelReader::DispatchInputData_max': 0.09600000083446503,
    'ChannelReader::DispatchInputData_count': 13,
    'MessageLoop::RunTask': 381.0659999921918,
    'MessageLoop::RunTask_avg': 0.10186206896343004,
    'MessageLoop::RunTask_max': 24.65199999883771,
    'MessageLoop::RunTask_count': 3741,
    'TaskQueueManager::ProcessTaskFromWorkQueue': 127.77200001478195,
    'TaskQueueManager::ProcessTaskFromWorkQueue_avg': 1.1722201836218529,
    'TaskQueueManager::ProcessTaskFromWorkQueue_max': 22.55800000205636,
    'TaskQueueManager::ProcessTaskFromWorkQueue_count': 109,
    TimerFire: 11.074000008404255,
    TimerFire_avg: 1.582000001200608,
    TimerFire_max: 3.309000000357628,
    TimerFire_count: 7,
    ResourceSendRequest: 6,
    FunctionCall: 14.994000010192394,
    FunctionCall_avg: 0.32595652196070424,
    FunctionCall_max: 3.1610000021755695,
    FunctionCall_count: 46,
    UpdateCounters: 46,
    ResourceReceiveResponse: 6,
    ResourceFinish: 6,
    ScheduleStyleRecalculation: 38,
    EventDispatch: 2.073999997228384,
    EventDispatch_avg: 0.3456666662047307,
    EventDispatch_max: 0.38500000163912773,
    EventDispatch_count: 6,
    TimerInstall: 6,
    BeginMainThreadFrame: 38,
    UpdateLayoutTree: 9.668000005185604,
    UpdateLayoutTree_avg: 0.2544210527680422,
    UpdateLayoutTree_max: 0.34200000017881393,
    UpdateLayoutTree_count: 38,
    UpdateLayerTree: 15.790000006556511,
    UpdateLayerTree_avg: 0.41552631596201345,
    UpdateLayerTree_max: 0.6609999984502792,
    UpdateLayerTree_count: 38,
    UpdateLayer: 1.8859999813139439,
    UpdateLayer_avg: 0.00496315784556301,
    UpdateLayer_max: 0.052000001072883606,
    UpdateLayer_count: 380,
    CompositeLayers: 8.25900000706315,
    CompositeLayers_avg: 0.21734210544903027,
    CompositeLayers_max: 0.671000000089407,
    CompositeLayers_count: 38,
    BeginFrame: 383,
    'ChannelMojo::OnMessageReceived': 24.093000072985888,
    'ChannelMojo::OnMessageReceived_avg': 0.05249019623744202,
    'ChannelMojo::OnMessageReceived_max': 2.1879999972879887,
    'ChannelMojo::OnMessageReceived_count': 459,
    'TaskGraphRunner::RunTask': 16.936000034213066,
    'TaskGraphRunner::RunTask_avg': 0.014739773746051406,
    'TaskGraphRunner::RunTask_max': 0.07999999821186066,
    'TaskGraphRunner::RunTask_count': 1149,
    RequestMainThreadFrame: 38,
    RequestAnimationFrame: 34,
    FireAnimationFrame: 7.970999997109175,
    FireAnimationFrame_avg: 0.24154545445785378,
    FireAnimationFrame_max: 0.7650000005960464,
    FireAnimationFrame_count: 33,
    'WorkerThread::ThreadMain::Run': 0.24799999967217445,
    'WorkerThread::ThreadMain::Run_avg': 0.24799999967217445,
    'WorkerThread::ThreadMain::Run_max': 0.24799999967217445,
    'WorkerThread::ThreadMain::Run_count': 1,
    'Looper.dispatchMessage': 94.21399995684624,
    'Looper.dispatchMessage_avg': 0.1847333332487181,
    'Looper.dispatchMessage_max': 0.7320000007748604,
    'Looper.dispatchMessage_count': 510,
    TracingStartedInBrowser: 1,
    Layers: 0,
    PaintedArea_total: 0,
    PaintedArea_avg: 0,
    NodePerLayout_avg: 0,
    ExpensivePaints: 0,
    ExpensiveEventHandlers: 0,
    'framesPerSec (devtools)': NaN,
    Styles: 9.668000005185604,
    Javascript: 14.994000010192394,
    numAnimationFrames: 100,
    numFramesSentToScreen: 100,
    droppedFrameCount: 5,
    meanFrameTime_raf: 17.326732673267326,
    framesPerSec_raf: 57.714285714285715,
    connectEnd: 1466752845899,
    connectStart: 1466752845834,
    domComplete: 1466752866196,
    domContentLoadedEventEnd: 1466752846068,
    domContentLoadedEventStart: 1466752846067,
    domInteractive: 1466752846067,
    domLoading: 1466752845998,
    domainLookupEnd: 1466752845834,
    domainLookupStart: 1466752829822,
    fetchStart: 1466752829793,
    firstPaint: 16532.6790809631,
    loadEventEnd: 1466752866199,
    loadEventStart: 1466752866196,
    navigationStart: 1466752829793,
    redirectEnd: 0,
    redirectStart: 0,
    requestStart: 1466752845900,
    responseEnd: 1466752845993,
    responseStart: 1466752845975,
    secureConnectionStart: 1466752845846,
    unloadEventEnd: 0,
    unloadEventStart: 0,
    loadTime: 36406,
    domReadyTime: 20129,
    readyStart: 0,
    redirectTime: 0,
    appcacheTime: 29,
    unloadEventTime: 0,
    domainLookupTime: 16012,
    connectTime: 65,
    requestTime: 93,
    initDomTreeTime: 74,
    loadEventTime: 3,
    NetworkImage: 41.3549999999959,
    NetworkImage_avg: 20.67749999999795,
    NetworkImage_max: 21.0199999999968,
    NetworkImage_count: 2,
    _browserName: 'android',
    _url: 'https://www.baidu.com/' } ]
      √ Actions:do nothing (77390ms)

  mocha:runner finished running +1m

  1 passing (1m)

  mocha:runner end +16ms

D:\node\MyNodeProject\browser-perf>

**Comment by drywind** [comment]
Below logs were outputed by browser-perf version @1.4.6,may this do you a favor.

D:\node\MyNodeProject\browser-perf>mocha ./test_on_hwb_youtube.js
  mocha:suite bail undefined +0ms
  mocha:suite enableTimeouts true +4ms
  mocha:suite bail undefined +6ms
  mocha:suite timeout 2000 +432ms
  mocha:suite retries -1 +1ms
  mocha:suite enableTimeouts true +0ms
  mocha:suite slow 75 +1ms
  mocha:suite bail undefined +0ms
  mocha:suite timeout 2000 +1ms
  mocha:suite retries -1 +0ms
  mocha:suite enableTimeouts true +0ms
  mocha:suite slow 75 +1ms
  mocha:suite bail undefined +0ms
  mocha:suite timeout 600000 +1ms
  mocha:runnable timeout 600000 +0ms
  mocha:runnable enableTimeouts true +1ms
  mocha:runnable timeout 75 +1ms
  mocha:runner grep /.*/ +0ms
  mocha:runner globals ["DTRACE_NET_SERVER_CONNECTION","DTRACE_NET_STREAM_END","
DTRACE_HTTP_SERVER_REQUEST","DTRACE_HTTP_SERVER_RESPONSE","DTRACE_HTTP_CLIENT_RE
QUEST","DTRACE_HTTP_CLIENT_RESPONSE","COUNTER_NET_SERVER_CONNECTION","COUNTER_NE
T_SERVER_CONNECTION_CLOSE","COUNTER_HTTP_SERVER_REQUEST","COUNTER_HTTP_SERVER_RE
SPONSE","COUNTER_HTTP_CLIENT_REQUEST","COUNTER_HTTP_CLIENT_RESPONSE","global","p
rocess","GLOBAL","root","Buffer","clearImmediate","clearInterval","clearTimeout"
,"setImmediate","setInterval","setTimeout","console","before","after","beforeEac
h","afterEach","run","context","describe","xcontext","xdescribe","specify","it",
"xspecify","xit","XMLHttpRequest","Date","errno"] +1ms
  mocha:runner globals [] +2ms
  mocha:runner start +0ms

  mocha:runner run suite  +2ms

  mocha:runner run suite End To End Test Cases +3ms
  End To End Test Cases
  mocha:runner run suite End To End Test Cases gets enough statistics from brows
ers +0ms
    gets enough statistics from browsers
  bp:index Selenium is on localhost +0ms
  bp:metrics Initializing Metrics +1ms
  bp:probes Registering probe +263ms PerfLogProbe
  bp:probes:AndroidTracingProbe Initialize +4ms
  bp:probes Registering probe +1ms AndroidTracingProbe
  bp:probes Registering probe +4ms PerfLogProbe
  bp:probes Registering probe +1ms AndroidTracingProbe
  bp:probes Registering probe +3ms RafBenchmarkingProbe
  bp:probes Registering probe +3ms NavTimingProbe
  bp:probes Registering probe +4ms NetworkResourcesProbe
  bp:metrics TimelineMetrics +1ms setup called
  bp:metrics ChromeTracingMetrics +1ms setup called
  bp:metrics NetworkResources +0ms setup called
  bp:probes setup +1ms
  bp:probes PerfLogProbe +0ms setup called
  bp:probes AndroidTracingProbe +1ms setup called
  bp:probes:AndroidTracingProbe Setting up android tracing +0ms
  bp:probes:AndroidTracingProbe $ adb server start +0ms
  bp:probes:AndroidTracingProbe $ adb logcat -c +43ms
  bp:probes NetworkResourcesProbe +37ms setup called
  bp:index Stating browser with +1ms {"browserName":"android","chromeOptions":{"
androidPackage":"com.android.chrome","androidDeviceSerial":"192.168.206.113:5555
","perfLoggingPrefs":{}},"loggingPrefs":{"performance":"ALL"}}
  bp:selenium CALL +1ms init({"browserName":"android","chromeOptions":{"androidP
ackage":"com.a
  bp:selenium RESPONSE +4s init({"browserName":"android","chromeOptions":{"andro
idPackage":"com.a "fec0e5d9a6339368bcc4067c58fcd2ca",{"acceptSslCerts":true,"app
lication
  bp:index Session is fec0e5d9a6339368bcc4067c58fcd2ca +2ms
  bp:index Running Prescript +1ms
  bp:selenium CALL +1ms get("https://www.baidu.com/")
  bp:selenium RESPONSE +37s get("https://www.baidu.com/")
  bp:probes start +2ms
  bp:probes PerfLogProbe +1ms start called
  bp:selenium CALL +1ms logTypes()
  bp:selenium RESPONSE +8ms logTypes() ["performance","browser","driver"]
  bp:probes:PerfLogProbe Supported log types +1ms [ 'performance', 'browser', 'd
river' ]
  bp:selenium CALL +5ms log("performance")
  bp:selenium RESPONSE +11ms log("performance") [{"level":"INFO","message":"{\"m
essage\":{\"method\":\"Page.frameAttac
  bp:probes AndroidTracingProbe +2ms start called
  bp:selenium CALL +0ms sessionCapabilities()
  bp:selenium RESPONSE +5ms sessionCapabilities() {"acceptSslCerts":true,"applic
ationCacheEnabled":false,"browserConnect
  bp:probes RafBenchmarkingProbe +1ms start called
  bp:selenium CALL +8ms execute("(function(){var getTimeMs=(function(){if(window
.performance)\
  bp:selenium RESPONSE +40ms execute("(function(){var getTimeMs=(function(){if(w
indow.performance)\ null
  bp:probes NetworkResourcesProbe +1ms start called
  bp:selenium CALL +2ms execute("(function(){window.__networkResources=(window.p
erformance&&ty
  bp:probes teardown +2ms
  bp:probes PerfLogProbe +1ms teardown called
  bp:probes:PerfLogProbe Getting Performance log +2ms http://localhost:9515/sess
ion/fec0e5d9a6339368bcc4067c58fcd2ca/log
  bp:selenium RESPONSE +973ms execute("(function(){window.__networkResources=(wi
ndow.performance&&ty null
  bp:selenium CALL +1ms eval("window.__networkResources")
  bp:probes AndroidTracingProbe +49ms teardown called
  bp:selenium CALL +1ms sessionCapabilities()
  bp:selenium RESPONSE +35ms eval("window.__networkResources") [{"connectEnd":0,
"connectStart":0,"domainLookupEnd":0,"domainLookupSta
  bp:selenium RESPONSE +1ms sessionCapabilities() {"acceptSslCerts":true,"applic
ationCacheEnabled":false,"browserConnect
  bp:probes RafBenchmarkingProbe +1ms teardown called
  bp:probes:RafBenchmarkingProbe Clearing timer Interval +0ms
  bp:selenium CALL +1ms eval("window.__RafRecorder.get()")
  bp:selenium RESPONSE +29ms eval("window.__RafRecorder.get()") [36535.649999998
,36552.3169999979,37252.3169999986]
  bp:probes NavTimingProbe +2ms teardown called
  bp:selenium CALL +7ms execute("(function(){var requestAnimationFrame=(function
(){return wind
  bp:selenium RESPONSE +30ms execute("(function(){var requestAnimationFrame=(fun
ction(){return wind null
  bp:selenium CALL +2ms waitFor({"asserter":{},"timeout":600000,"pollFreq":1000}
)
  bp:selenium CALL +2ms eval("(typeof window.__navTimings !== \"undefined\")")
  bp:selenium RESPONSE +34ms eval("(typeof window.__navTimings !== \"undefined\"
)") false
  bp:selenium CALL +1s eval("(typeof window.__navTimings !== \"undefined\")")
  bp:selenium RESPONSE +35ms eval("(typeof window.__navTimings !== \"undefined\"
)") true
  bp:selenium RESPONSE +1ms waitFor({"asserter":{},"timeout":600000,"pollFreq":1
000}) true
  bp:selenium CALL +1ms eval("window.__navTimings")
  bp:selenium RESPONSE +31ms eval("window.__navTimings") {"connectEnd":146675337
3569,"connectStart":1466753373506,"domComplete"
  bp:probes NetworkResourcesProbe +2ms teardown called
  bp:selenium CALL +2ms execute("(function(){window.__networkResources=(window.p
erformance&&ty
  bp:selenium RESPONSE +32ms execute("(function(){window.__networkResources=(win
dow.performance&&ty null
  bp:selenium CALL +2ms eval("window.__networkResources")
  bp:selenium RESPONSE +49ms eval("window.__networkResources") [{"connectEnd":0,
"connectStart":0,"domainLookupEnd":0,"domainLookupSta
  bp:metrics Getting Results +4ms
  bp:metrics Getting results from  +1ms TimelineMetrics
  bp:metrics Getting results from  +1ms ChromeTracingMetrics
  bp:metrics:RenderingStats Looked at all events, could not find a process_label
s. Pid is undefined +1ms
  bp:metrics:RenderingStats Process ID for render process is  +1ms undefined
  bp:metrics:RenderingStats Timestamp Event name is  +1ms BenchmarkInstrumentati
on::ImplThreadRenderingStats
  bp:metrics:ChromeTracingMetrics Does not have enough frames for computing trac
ing +1ms
  bp:metrics:ChromeTracingMetrics Does not have enough frames for computing trac
ing +1ms
  bp:metrics Getting results from  +1ms RafBenchmarkingRenderingStats
  bp:metrics Getting results from  +1ms NetworkTimings
  bp:metrics Getting results from  +1ms NetworkResources
  bp:selenium CALL +5ms quit()
  bp:selenium RESPONSE +703ms quit()
[ { Styles: 0,
    Javascript: 0,
    numAnimationFrames: 2,
    numFramesSentToScreen: 2,
    droppedFrameCount: 38,
    meanFrameTime_raf: 238.8890000001993,
    framesPerSec_raf: 4.186044564626942,
    connectEnd: 1466753373569,
    connectStart: 1466753373506,
    domComplete: 1466753399852,
    domContentLoadedEventEnd: 1466753373882,
    domContentLoadedEventStart: 1466753373882,
    domInteractive: 1466753373882,
    domLoading: 1466753373655,
    domainLookupEnd: 1466753373506,
    domainLookupStart: 1466753363672,
    fetchStart: 1466753363669,
    firstPaint: 10336.6830348969,
    loadEventEnd: 1466753399855,
    loadEventStart: 1466753399852,
    navigationStart: 1466753363459,
    redirectEnd: 0,
    redirectStart: 0,
    requestStart: 1466753373569,
    responseEnd: 1466753373663,
    responseStart: 1466753373646,
    secureConnectionStart: 1466753373518,
    unloadEventEnd: 0,
    unloadEventStart: 0,
    loadTime: 36186,
    domReadyTime: 25970,
    readyStart: 210,
    redirectTime: 0,
    appcacheTime: 3,
    unloadEventTime: 0,
    domainLookupTime: 9834,
    connectTime: 63,
    requestTime: 94,
    initDomTreeTime: 219,
    loadEventTime: 3,
    NetworkImage: 347.8749999999783,
    NetworkImage_avg: 38.65277777777536,
    NetworkImage_max: 83.3450000000012,
    NetworkImage_count: 9,
    _browserName: 'android',
    _url: 'https://www.baidu.com/' } ]
      √ Actions:do nothing (44313ms)

  mocha:runner finished running +44s

  1 passing (44s)

  mocha:runner end +1ms

D:\node\MyNodeProject\browser-perf>

**Comment by axemclion** [comment]
@drywind I just added a fix and pushed 1.4.10. Can you check now please ?

**Comment by axemclion** [comment]
@drywind Closing this issue since this should be fixed. If not, can you please reopen the issue ?
