### ISSUE TITLE
How to performance of multiple steps?

### ISSUE THREAD

**Issue by usherfu** [axemclion/browser-perf#71]
Currently I am trying to integrate browser-perf with our CI pipeline.  I have following questions and appreciate if anyone could give some advises:

The scenario is that end user will navigate on our web app multiple consecutive steps, e.g. navigate to the app, fill out search criteria, click "search" button, select one result from the list to navigate to the item detail, click edit button and etc.   All the steps are written in one single selenium script to simulate the user interaction with the apps

Questions:
- Once the test finishes, browser-perf return a number of metrics.  How do I interpret those metrics? Are those metrics measurement of last step, all steps together or something else?
- If I'd like measure the performance of each of above steps separately, how to do it?  With [webpagetest scripting ](https://sites.google.com/a/webpagetest.org/docs/using-webpagetest/scripting) , in the script I can specify logData to 0 or 1, in order to toggle whether to measure next step or not, something like following:

```
logData    0
// put any urls you want to navigate
navigate    www.aol.com
navigate    news.aol.com

logData    1
// this step will get recorded
navigate    news.aol.com/world
```
How to achieve similar purpose with browser-perf?

Thanks!

**Comment by axemclion** [comment]
Answering your questions 

1. The metrics that are collected are for the entire duration of the test. It is the equivalent of click *Start Profiling* in the timeline, performing the actions and then *Stop Profiling*

2. For measuring the scripts separately, you would have to manually call `browser.log("performance")`. That returns a promise with all the timeline data. This is exactly what webpagetest also does.

**Comment by usherfu** [comment]
@axemclion 
Thanks for the feedback. I spent sometime trying to investigate different way of taking measurement.  The example scenario below is  to navigate to google.com, type some keyword, and then click on go button.  And I'd like to measure only the step of "click GO button".  I created following two scripts:

As you can see from below code, the only difference is that in "WithPrescript" case, the preceding steps are in "preScript" section, whereas in case of "noPrescript", everything is writting in the "actions" section. 

I did this based on the wiki page "The preScript key in the options object runs a selenium script before the metrics are measured."

- WithPrescript: 
```
    actions: [
    function(browser) {
		return browser.elementByCssSelector("button[name='btnG']")
		.then(function(el) {
	    		return el.click();
		}).catch(function(err) {
                        console.log(err);
      	        });
    }],

    preScript:
	function(browser){
		return browser.get('http://www.google.com').then(function(){
				return browser.elementByCssSelector("#lst-ib");
		}).then(function(el) {
	    		return el.type("performance");
                 }).catch(function(err) {
					console.log(err);
		});
	}
```

- NoPrescript: 
```
    actions: [
    function(browser) {
        return browser.elementByCssSelector("#lst-ib")
        .then(function(el) {
	    	return el.type("performance");
      }).then(function() {
	    	return browser.elementByCssSelector("button[name='btnG']");
      }).then(function(el) {
	    	return el.click();
      }).catch(function(err) {
                console.log(err);
      });
    }]
```

Questions:
 1. Is this the correct way to get performance measurement of certain step preceding which there are always some "preparatory" steps?
 2. Attached are the output of both script executed in the same environment, my understanding is that, WithPrescript should only measure "click GO", whereas "NoScript" would measure the while scenario. does the number look resonable?

The "loadTime" of withPrescript (520ms) is less than the one for noPrescript (993ms), which seems to be reasable, however, not sure if the rest metrics actually contradict my assumption. What do you think?  

[noPrescript.txt](https://github.com/axemclion/browser-perf/files/503071/noPrescript.txt)
[withPrescript.txt](https://github.com/axemclion/browser-perf/files/503070/withPrescript.txt)
