### ISSUE TITLE
JavaScript heap out of memory

### ISSUE THREAD

**Issue by khanhlhq** [axemclion/browser-perf#75]
Hi,
When I used this module, I got an error. Would you have the solution for this?

<--- Last few GCs --->

[9339:0x102804600]    22552 ms: Mark-sweep 1117.8 (1135.4) -> 862.8 (880.4) MB, 263.7 / 0.0 ms  allocation failure GC in old space requested
[9339:0x102804600]    22848 ms: Mark-sweep 862.8 (880.4) -> 862.8 (880.4) MB, 295.5 / 0.0 ms  allocation failure GC in old space requested
[9339:0x102804600]    23458 ms: Mark-sweep 862.8 (880.4) -> 862.8 (869.4) MB, 610.2 / 0.0 ms  last resort gc 
[9339:0x102804600]    23717 ms: Mark-sweep 862.8 (869.4) -> 862.7 (869.4) MB, 258.8 / 0.0 ms  last resort gc 

<--- JS stacktrace --->

==== JS stack trace =========================================

Security context: 0xcb8d9c0d31 <JS Object>
    2: /* anonymous */ [/usr/local/lib/node_modules/browser-perf/node_modules/wd/lib/utils.js:~102] [pc=0xa0f61aa4753](this=0x1e19466a9fd9 <JS Global Object>,i=50139473)
    3: times [/usr/local/lib/node_modules/browser-perf/node_modules/lodash/index.js:~11490] [pc=0xa0f61ab9e94](this=0x1cdbecb74fe9 <JS Function lodash (SharedFunctionInfo 0xd8939f32cd1)>,n=54410852,iteratee=0x1cdbecb93019 <JS Fun...

FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory
 1: node::Abort() [/usr/local/bin/node]
 2: node::FatalException(v8::Isolate*, v8::Local<v8::Value>, v8::Local<v8::Message>) [/usr/local/bin/node]
 3: v8::Utils::ReportOOMFailure(char const*, bool) [/usr/local/bin/node]
 4: v8::internal::V8::FatalProcessOutOfMemory(char const*, bool) [/usr/local/bin/node]
 5: v8::internal::Factory::NewUninitializedFixedArray(int) [/usr/local/bin/node]
 6: v8::internal::(anonymous namespace)::ElementsAccessorBase<v8::internal::(anonymous namespace)::FastPackedObjectElementsAccessor, v8::internal::(anonymous namespace)::ElementsKindTraits<(v8::internal::ElementsKind)2> >::ConvertElementsWithCapacity(v8::internal::Handle<v8::internal::JSObject>, v8::internal::Handle<v8::internal::FixedArrayBase>, v8::internal::ElementsKind, unsigned int, unsigned int, unsigned int, int) [/usr/local/bin/node]
 7: v8::internal::(anonymous namespace)::ElementsAccessorBase<v8::internal::(anonymous namespace)::FastPackedObjectElementsAccessor, v8::internal::(anonymous namespace)::ElementsKindTraits<(v8::internal::ElementsKind)2> >::GrowCapacityAndConvertImpl(v8::internal::Handle<v8::internal::JSObject>, unsigned int) [/usr/local/bin/node]
 8: v8::internal::Runtime_GrowArrayElements(int, v8::internal::Object**, v8::internal::Isolate*) [/usr/local/bin/node]
 9: 0xa0f616063a7
10: 0xa0f61a365fc
Abort trap: 6

**Comment by axemclion** [comment]
Thanks for reporting the issue. Closing this issue now, since there is no active work required on this. If you still have the issue or need help, please reopen the issue.
