### ISSUE TITLE
browser-perf fails with cordova-plugin-crosswalk-webview

### ISSUE THREAD

**Issue by SunboX** [axemclion/browser-perf#76]
If I'm running a hybrid Cordova app using the `cordova-plugin-crosswalk-webview` plugin, browser-perf fails with `"chrome not reachable\\n  (Driver info: chromedriver=2.27.440174 (e97a722caafc2d3a8b807ee115bfb307f7d2cfd9),platform=Windows NT 10.0.14393 x86_64)"`

If I'm building the app without `cordova-plugin-crosswalk-webview`, browser-perf works as expected.

If I have `cordova-plugin-crosswalk-webview` enabled, I can connect the Chrome Developer Tools to the running app. So basically this should work using `cordova-plugin-crosswalk-webview`.
I don't know, why browser-perf (or the chromedriver) fails.

**Comment by axemclion** [comment]
Thanks for reporting this issue. I think the trick here is to see how we can connect selenium to crosswalk.

**Comment by axemclion** [comment]
@SunboX Were you able to find a resolution to this issue ?

**Comment by axemclion** [comment]
Closing this since Cross walk is now being deprecated. https://crosswalk-project.org/blog/crosswalk-final-release.html
