### ISSUE TITLE
maxInstances support?

### ISSUE THREAD

**Issue by jahnavi310** [axemclion/browser-perf#78]
Hey,

Does this support the maxInstances property to run multiple instances of the browser?

Thanks,
-Jahnavi

**Comment by axemclion** [comment]
Do you have a reference to the maxInstances property? If it can be passed as a capability, I guess it can be used.

**Comment by jahnavi310** [comment]
so, i was referring to the maxinstances property that the protractor.conf file has, can that be incorporated in the config for browser-perf? 

I am mainly trying to achieve running the performance tests in parallel for different urls so that it will make the process more faster.

Currently i have the urls stored in a .txt file from where it picks them up, reads them, performs the performance test, stores them to the db and then goes to the next one and this is kind of very slow.

**Comment by jahnavi310** [comment]
Is it possible to run browser-perf on the 3 different urls on three different chrome instances on the selenium grid at the same time?

**Comment by axemclion** [comment]
The simplest way to do this would be to have 3 instances of browser-perf, each hitting a separate selenium instance. I am not sure how that maps to capabilities.

**Comment by axemclion** [comment]
Closing this issue - please re-open if you this it is still not resolved.
