### ISSUE TITLE
Cannot find module './index.js

### ISSUE THREAD

**Issue by premkh9** [axemclion/browser-perf#80]
Hi ,
I am observing '[11:32:38] E/launcher - Error: Error: Cannot find module './index.js'' when I try to execute the configuration file. I tried placing index file in different location and still observed the same error

This is my file structure. Not sure what is wrong with it. Please help me

![image](https://cloud.githubusercontent.com/assets/14880073/22077683/7668cd84-dd72-11e6-83b9-37ead3608976.png)

**Comment by axemclion** [comment]
`./index.js` refers to a file on your local project. What are you using for perfRunner ?

**Comment by premkh9** [comment]
Documentation asked to use index.js file and I am using the same for perfrunner. Do I need to place index.js somewhere else ?

![image](https://cloud.githubusercontent.com/assets/14880073/22080287/46f017c4-dd7c-11e6-8763-0607862af803.png)
