### ISSUE TITLE
Undefined metric on a specific page

### ISSUE THREAD

**Issue by naxhh** [axemclion/browser-perf#84]
hi everyone. I'm testing the tool for the very first time.

And I found a case when there's a metric returned with `undefined: 6` what does this means?

I've tested it in chrome 49 and 56 and happens in both. I've tested the same website in another url and it does not happen. I've tested other web pages and I don't get to reproduce it.

```
rowser-perf -s selenium -u user -a pass --browsers=chrome -o json --all "http://www.fotocasa.es/es/alquiler/casas/barcelona-capital/todas-las-zonas/l"
[ { undefined: 6,
    Styles: 0,
    Javascript: 0,
    numAnimationFrames: 823,
    numFramesSentToScreen: 823,
    droppedFrameCount: 163,
... 
```

**Comment by axemclion** [comment]
Undefined are usually caused when some labels are not populated in the results. You can ignore these numbers.

**Comment by naxhh** [comment]
ok! thanks for the answer and for the project :)
