### ISSUE TITLE
Run the node module multiple times

### ISSUE THREAD

**Issue by PatrickDai** [axemclion/browser-perf#90]
How could I run `browserPerf(...)` 5 times in a row ?

I tried to do that within a for loop, it opens me 5 Chrome but it seems that only the 1st one ends correctly. The others don't return me any metrics 

```
const browserPerf = require('browser-perf');

for (let i = 0; i < 5; i++) {
  browserPerf(myUrl, (err, res) => console.log('res: ', res)); 
} 
```
output:
> res: [ { connectedEnd: ..., ...}]
> res: []
> res: []
> res: []
> res: []

**Comment by axemclion** [comment]
browserPerf returns a callback - so you cannot just use a sync loop. You would have to call the furthur iterations in a callback.
