### ISSUE TITLE
browser-perf suddenly stops after successfully launched

### ISSUE THREAD

**Issue by chinhnguyen8855** [axemclion/browser-perf#92]
Hi,
I tried this tool manually, but I'm not able to get it work, or may be something I have missed.
I have selenium started, then I execute the following command:
browser-perf --selenium=http://localhost:4444/wd/hub --browsers=chrome http://sap-splash-ci.mo.sap.corp:8000
After Chrome started for 10 seconds, then it stops.  Is it expected?  I thought i could manually perform some actions on the browser, then the tool will collect the performance metric.
Here is log:

![image](https://user-images.githubusercontent.com/3290297/35887391-f9a33dc4-0b48-11e8-97b9-cf38757b66e8.png)

![image](https://user-images.githubusercontent.com/3290297/35887404-032a5ac6-0b49-11e8-8fa1-b8df8aab0798.png)

**Comment by axemclion** [comment]
You cannot perform manual actions. The actions need to be written using selenium. If you are looking for performing manual actions and collecting perflog, I would recommend using Chrome directly, and saving the perflog. 

Browser-perf simply automates that process.
